# Use a Node.js image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally (if it's not in your `package.json`)
RUN npm install -g nodemon

# Copy the rest of the application code
COPY . .

# Expose the application's port
EXPOSE 8000

# Start the application in development mode
CMD ["npm", "run", "dev"]
